blog/api/urls.py
from django.urls import path
from blog.api.views import *


app_name = 'blog_api'

urlpatterns = [
    path('', blog_api),
    path('blogs', blog_view),
    path('blog_detail/<int:pk>', blog_detail),
    path('blog_create', blog_create),
    path('blog_update/<int:pk>', blog_update),
    path('blog_delete/<int:pk>', blog_delete),
    path('create_blog_comment/<int:pk>', create_blog_comment),
    path('blog_comments/<int:pk>', comments_blog_view),

    path('news', news_view),
    path('news_detail/<int:pk>', news_detail),
    path('news_create', news_create),
    path('news_update/<int:pk>', news_update),
    path('news_delete/<int:pk>', news_delete),

    path('posts', post_view),

    path('about', about_view),
    path('contact', contact_view)
]

blog/urls.py
from django.urls import path

from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('marble/', blog_view, name='blog_view'),
    path('add_blog/', create_blog, name='add_blog'),
    path('detail/<int:pk>', detail_blog, name='blog_detail'),
    path('edit_blog/<int:pk>', edit_blog, name='edit_blog'),
    path('delete/<int:pk>/', delete_blog, name='delete_blog'),



    path('add_news/', create_news, name='news_add'),
    path('news/', news_view, name='news'),
    path('news_detail/<int:pk>', detail_news, name='news_detail'),
    path('edit_news/<int:pk>', edit_news, name='edit_news'),
    path('delete_news/<int:pk>/', delete_news, name='delete_news'),


    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('posts/', posts_view, name='posts'),
    path('add_comment_blogs/<int:pk>', blog_comment, name='blog_comment'),
    path('add_comment/<int:pk>', post_comment, name='post_comment'),

]

django_app/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),

    path('api/v1/', include('blog.api.urls')),
    path('api/v1/', include('account.api.urls')),

    path('api/v1/drf-auth/', include('rest_framework.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken'))
    # path('api/v1/auth/', include('djoser.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('blogs/', include('blog.urls')),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/api/views.py
from django.db.models import Q
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from blog.models import BlogPostModel, CommentModel, NewsBlogModel, AboutModel, ContactModel
from blog.api.serializers import BlogSerializer, CreateBlogSerializer, CommentsSerializer, NewsSerializer, CreateNewsSerializer, AboutSerializer, ContactSerializer
from rest_framework.pagination import PageNumberPagination


@api_view(['GET'])
def blog_api(request):
    api_urls = {
        'Blogs': 'blogs/',
        'Detail View': 'blog_detail/<str:pk>',
        'Create': 'blog_create',
        'Update': 'blog_update/<int:pk>',
        'Delete': 'blog_delete/<int:pk>',
    }
    return Response(api_urls)


@api_view(['GET', ])
@permission_classes([AllowAny, ])
def blog_view(request):
    user = request.user
    paginator = PageNumberPagination()
    paginator.page_size = 2
    blogs = BlogPostModel.objects.filter(author=user.id).order_by('-id')
    result_page = paginator.paginate_queryset(blogs, request)
    serializer = BlogSerializer(result_page, many=True)
    return paginator.get_paginated_response(serializer.data)


@api_view(['GET'])
def blog_detail(request, pk):
    user = request.user
    blog_post = get_object_or_404(BlogPostModel, pk=pk)
    if blog_post.author != user:
        return Response({'message': 'You are not the author of that post.'})
    serializer = BlogSerializer(blog_post, many=False)
    return Response(serializer.data)


@api_view(['POST'])
def blog_create(request):
    serializer = CreateBlogSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save(author=request.user)
    return Response(serializer.data)


@api_view(['POST'])
def blog_update(request, pk):
    user = request.user
    blog_post = get_object_or_404(BlogPostModel, pk=pk)
    if blog_post.author != user:
        return Response({'message': 'You are not the author of that post.'})
    serializer = CreateBlogSerializer(instance=blog_post, data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)


@api_view(['DELETE'])
def blog_delete(request, pk):
    blog = BlogPostModel.objects.get(id=pk)
    blog.delete()
    return Response('Item successfully deleted!')


#*********************comments


@api_view(['POST'])
def create_blog_comment(request, pk):
    user = request.user
    blog = get_object_or_404(CommentModel, pk = pk)
    comment = CommentModel(author=user)

    serializer = CommentsSerializer(comment, data=request.data)
    if serializer.is_valid():
        # serializer.author = user
        # serializer.blog = blog
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def comments_blog_view(request, pk):
    comments = CommentModel.objects.filter(post_id=pk)
    serializer = CommentsSerializer(comments, many=True)
    return Response(serializer.data)


#*********************news


@api_view(['GET', ])
@permission_classes([AllowAny, ])
def news_view(request):
    user = request.user
    paginator = PageNumberPagination()
    paginator.page_size = 2
    news = NewsBlogModel.objects.all()
    result_page = paginator.paginate_queryset(news, request)
    serializer = NewsSerializer(result_page, many=True)
    return paginator.get_paginated_response(serializer.data)


@api_view(['GET'])
def news_detail(request, pk):
    user = request.user
    news_post = get_object_or_404(NewsBlogModel, pk=pk)

    serializer = NewsSerializer(news_post, many=False)
    return Response(serializer.data)


@api_view(['POST'])
def news_create(request):
    user = request.user

    if not user.is_superuser:
        return Response("Only an admin can create a post!")

    serializer = CreateNewsSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save(author=request.user)
    return Response(serializer.data)


@api_view(['POST'])
def news_update(request, pk):
    user = request.user

    if not user.is_superuser:
        return Response("Only an admin can update a post!")

    news_post = get_object_or_404(NewsBlogModel, pk=pk)

    serializer = CreateNewsSerializer(instance=news_post, data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)


@api_view(['DELETE'])
def news_delete(request, pk):
    user = request.user

    if not user.is_superuser:
        return Response("Only an admin can delete a post!")
    news = NewsBlogModel.objects.get(id=pk)
    news.delete()
    return Response('Item successfully deleted!')


#*********************post


@api_view(['GET', ])
def post_view(request):
    user = request.user
    paginator = PageNumberPagination()
    paginator.page_size = 2

    posts = BlogPostModel.objects.filter(~Q(author=user))

    result_page = paginator.paginate_queryset(posts, request)
    serializer = BlogSerializer(result_page, many=True)
    return paginator.get_paginated_response(serializer.data)


#*********************other pages


@api_view(['GET', ])
def about_view(request):
    about = AboutModel.objects.all()
    serializer = AboutSerializer(about, many=True)
    return Response(serializer.data)


@api_view(['GET', ])
def contact_view(request):
    about = ContactModel.objects.all()
    serializer = ContactSerializer(about, many=True)
    return Response(serializer.data)

blog/views.py
from pyexpat.errors import messages
import email
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView

from blog.forms import BlogPostModel, NewsBlogForm, UpdateBlogPostForm, UpdateNewsPostForm, CreateBlogPostForm, CommentForm
from blog.models import BlogPostModel, NewsBlogModel, AboutModel, ContactModel, CommentModel
from account.models import Account
from django.core.paginator import Paginator
from django.db.models import Q



#BLOGS


@login_required
def blog_view(request):
    context = {}
    user = request.user
    sidebar = Account.objects.filter(id=user.id)
    blogs = BlogPostModel.objects.filter(author=user.id)

    paginator = Paginator(blogs, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context['sidebar'] = sidebar
    context['blog'] = blogs
    context['page_obj'] = page_obj

    return render(request, 'blog_posts.html', context)




@login_required
def create_blog(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect("account:signin")

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = BlogPostModel()
        return redirect("blog:blog_view")

    sidebar = Account.objects.filter(id=user.id)
    context['form'] = form
    context['sidebar'] = sidebar

    return render(request, "create_blog.html", context)


@login_required
def detail_blog(request, pk):
    context = {}
    user = request.user

    blog_post = get_object_or_404(BlogPostModel, pk=pk)
    sidebar = Account.objects.filter(id=user.id)
    context['sidebar'] = sidebar
    context['blog_detail'] = blog_post

    return render(request, 'blog_detail.html', context)


@login_required
def edit_blog(request, pk):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    blog_post = get_object_or_404(BlogPostModel, pk=pk)

    if blog_post.author != user:
        return HttpResponse('You are not the author of that post.')

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated"
            blog_post = obj
            return redirect('blog:blog_view')
    form = UpdateBlogPostForm(
        initial={
            'title': blog_post.title,
            'body': blog_post.body,
            'image': blog_post.image,
        }
    )
    sidebar = Account.objects.filter(id=user.id)
    context['sidebar'] = sidebar
    context['form'] = form
    return render(request, 'blog_edit.html', context)

@login_required
def delete_blog(request, pk):
    try:
        blog = BlogPostModel.objects.get(id=pk)
    except:
        return HttpResponse("This blog not found!")

    blog.delete()
    return redirect('blog:blog_view')


#NEWS


@login_required
def news_view(request):
    context = {}
    user = request.user

    sidebar = Account.objects.filter(id=user.id)
    blogs = NewsBlogModel.objects.all()

    paginator = Paginator(blogs, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context['page_obj'] = page_obj
    context['sidebar'] = sidebar
    context['news'] = blogs
    return render(request, 'news.html', context)


@login_required
def create_news(request):

    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect("account:signin")

    if not user.is_superuser:
        return HttpResponse("Only an admin can create a post!")

    form = NewsBlogForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        obj = form.save(commit=False)
        # print(obj.author)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        # print(obj.author)
        obj.save()
        form = NewsBlogForm()
        return redirect("blog:news")

    sidebar = Account.objects.filter(id=user.id)
    context['news'] = form
    context['sidebar'] = sidebar

    return render(request, "create_news.html", context)


@login_required
def detail_news(request, pk):
    context = {}
    user = request.user

    news_post = get_object_or_404(NewsBlogModel, pk=pk)
    sidebar = Account.objects.filter(id=user.id)
    context['sidebar'] = sidebar
    context['news_detail'] = news_post

    return render(request, 'news_detail.html', context)


@login_required
def edit_news(request, pk):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('account:signin')

    if not user.is_superuser:
        return HttpResponse("Only an admin can edit a post!")

    blog_news = get_object_or_404(NewsBlogModel, pk=pk)

    if blog_news.author != user:
        return HttpResponse('You are not the author of that post.')

    if request.POST:
        form = UpdateNewsPostForm(request.POST or None, request.FILES or None, instance=blog_news)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated"
            blog_post = obj
            return redirect('blog:news')
    form = UpdateNewsPostForm(
        initial={
            'title': blog_news.title,
            'body': blog_news.body,
            'image': blog_news.image,
        }
    )
    sidebar = Account.objects.filter(id=user.id)
    context['sidebar'] = sidebar
    context['form'] = form
    return render(request, 'news_edit.html', context)


@login_required
def delete_news(request, pk):
    user = request.user

    if not user.is_superuser:
        return HttpResponse("Only an admin can delete a post!")

    try:
        news = NewsBlogModel.objects.get(id=pk)
    except:
        return HttpResponse("This blog not found!")

    news.delete()
    return redirect('blog:news')


#OTHER PAGES


@login_required
def contact_view(request):
    context = {}
    user = request.user
    sidebar = Account.objects.filter(id=user.id)
    contact_data = ContactModel.objects.all()
    context['sidebar'] = sidebar
    context['contact_data'] = contact_data
    return render(request, 'contact.html', context)


@login_required
def about_view(request):
    context = {}
    user = request.user
    sidebar = Account.objects.filter(id=user.id)
    about_data = AboutModel.objects.all()
    context['sidebar'] = sidebar
    context['about_data'] = about_data
    return render(request, 'about.html', context)

#POSTS

@login_required
def posts_view(request):
    context = {}
    user = request.user
    sidebar = Account.objects.filter(id=user.id)

    blogs = BlogPostModel.objects.filter(author=user.id)

    posts = BlogPostModel.objects.filter(~Q(author=user))
    paginator = Paginator(posts, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context['sidebar'] = sidebar
    context['blog'] = blogs
    context['page_obj'] = page_obj
    context['posts'] = posts
    return render(request, 'posts.html', context)


#COMMENT

@login_required
def blog_comment(request, pk):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect("account:signin")

    post = get_object_or_404(BlogPostModel, pk=pk)

    form = CommentForm(request.POST or None, request.FILES or None)

    if form.errors:
        return HttpResponse(form.errors)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.post = post
        obj.save()
        form = CommentModel()
        return redirect("blog:blog_view")

    sidebar = Account.objects.filter(id=user.id)
    context['form'] = form
    context['sidebar'] = sidebar

    return render(request, "add_comment.html", context)


@login_required
def post_comment(request, pk):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect("account:signin")

    post = get_object_or_404(BlogPostModel, pk=pk)

    form = CommentForm(request.POST or None, request.FILES or None)
    print(form.errors)
    if form.errors:
        return HttpResponse(form.errors)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.post = post
        obj.save()
        form = CommentModel()
        return redirect("blog:posts")

    sidebar = Account.objects.filter(id=user.id)
    context['form'] = form
    context['sidebar'] = sidebar

    return render(request, "add_comment.html", context)

blog/templates/blog_detail.html
{% extends 'base_multilang.html' %}
{% load static %}
{% load i18n %}

{% block content %}
   <style>
            *{
        padding: 0;
        margin: 0;
    }
    .hero{
        max-width: 100%;
        height: 100vh;
        background-color: #292828;
        background-color: rgba(#000,#000,#000, 0.1);
<!--        filter: grayscale(100%);-->
        display: flex;
        /* padding: 0 100px; */
        /* align-items: center; */
        /* flex-direction: column; */
        background-repeat: no-repeat;
        background-size: cover;
        /* justify-content: center; */
        background-position: center;
        position: relative;
        margin-left:200px;
    }
    .hero h1{
        font-size: 18px;
        color: #FFFFFF;
        font-weight: 800;
    }
    .hero img{
    height:500px;
    width:50%;
<!--    object-fit:cover;-->
    }
    .hero button{
        width: 200px;
        height: 40px;
        border: 1px solid white;
        background-color: #FFFFFF;
        transition: all 0.2s linear;
        color: white;
        font-size: 20px;
        font-weight: 700;
        cursor: pointer;
        letter-spacing: 4px;
        margin-top: 30px;
    }
    .hero button:hover{
        background-color: white;
        color: black;
    }
    .shadow{
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        background-color: #494848;
        opacity: 1;

    }
    .text{
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        color: white;
        padding: 0 100px;
    }
    </style>

    <div class="hero">
            <!-- <h1>Mi sozdayom budushee</h1>
            <button>Discover</button> -->
            <div class="shadow">

            </div>

            <div class="text">
<!--                <h5>By:{{ blog_detail.author }}-{{ blog_detail.id }}</h5>-->
<!--                <h5>{{ user.id }}- {{ blog_detail.author.id }}</h5>-->
                <br>
                <p></p>
                <h1>{{ blog_detail.title }}</h1>
                <br>
                <img src='{{ blog_detail.imageURL }}' alt="">
                <br>
              <div class="sometext">
                <h3>{{ blog_detail.body }}</h3>
                  {% if user.id == blog_detail.author.id %}
                        <p align="right"><a href="{% url 'blog:edit_blog' blog_detail.pk %}" type="button" class="btn btn-md btn-outline-secondary">Edit</a> <a href="{% url 'blog:delete_blog' blog_detail.pk %}" type="button" class="btn btn-md btn-outline-secondary">Delete</a></p>
                  {% endif %}
              </div>
            </div>
            </div>
    </div>
{% endblock %}

blog/templates/blog_posts.html
{% extends 'base_multilang_pagination.html' %}
{% load static %}

{% block content %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }
      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }
      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }
      .nav-scroller {
<!--        position: relative;-->
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }
      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      img{
        object-fit: cover !important;
      }
    </style>
<body>
    <div class="album py-5" style="padding-left:280px; background-color:white">
      <div class="container ">
          <div class="row">
          {% for post in page_obj %}
          <div class="col-4">
            <div class="card  ">
              <img height="300px" width="100%" src='{{ post.imageURL }}' alt="">
              <div class="card-body ">
                  <p class="card-text">{{ post.title }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">{{ post.publish_date }}</small>
                  <div class="btn-group">
                       <a href="{% url 'blog:blog_detail' post.id %}" type="button" class="btn btn-sm btn-outline-secondary">More</a>
                  </div>
                </div>
                  <h6>Comments...</h6>
                  {% if not post.comments.all %}
                    No Comments Yet... <a href="{% url 'blog:blog_comment' post.pk %}">Add One</a>
                  {% else  %}
                    {% for comment in post.comments.all %}
                        <strong>
                            {{ comment.name }} - {{ comment.date_added }}
                        </strong>
                        <br>
                        {{ comment.body }}
                    <br>
                    {% endfor %}
                  {% if post.comments.all %}
                        <a href="{% url 'blog:blog_comment' post.pk %}">Add More</a>
                      {% endif %}
                  {% endif %}
              </div>
            </div>

          </div>
          {% endfor %}
              <br>
              <p></p>
              <br>
          <p align="right"><a href="{% url 'blog:add_blog' %}" type="button" class="btn btn-md btn-outline-secondary">Add</a></p>
          <br/><br/>
          </div>
      </div>
    </div>
</body>
{% endblock %}

blog/templates/news.html
{% extends 'base_multilang_pagination.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>
<body>
    <div class="album py-5" style="padding-left:280px; background-color:white">
      <div class="container">
          <div class="row">
          {% for post in page_obj %}
          <div class="col-4">
            <div class="card  ">
              <img height="300px" width="100%" src='{{ post.imageURL }}' alt="">
              <div class="card-body ">
                  <p class="card-text">{{ post.title }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">{{ post.publish_date }}</small>
                  <div class="btn-group">
                    <a href="{% url 'blog:news_detail' post.id %}" type="button" class="btn btn-sm btn-outline-secondary">More</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
              <br>
              <p></p>
              <p></p>
        {% if user.is_superuser %}
          <p align="right"><a href="{% url 'blog:news_add' %}" type="button" class="btn btn-md btn-outline-secondary">Add</a></p>
        {% endif %}
              <br/><br/>
          </div>
      </div>
    </div>
</body>
{% endblock %}

blog/templates/news_detail.html
{% extends 'base_multilang.html' %}
{% load static %}
{% load i18n %}

{% block content %}
   <style>
            *{
        padding: 0;
        margin: 0;
    }
    .hero{
        max-width: 100%;
        height: 100vh;
        background-color: #292828;
        background-color: rgba(#000,#000,#000, 0.1);
<!--        filter: grayscale(100%);-->
        display: flex;
        /* padding: 0 100px; */
        /* align-items: center; */
        /* flex-direction: column; */
        background-repeat: no-repeat;
        background-size: cover;
        /* justify-content: center; */
        background-position: center;
        position: relative;
        margin-left:200px;
    }
    .hero h1{
        font-size: 18px;
        color: #FFFFFF;
        font-weight: 800;
    }
    .hero img{
    height:500px;
    width:50%;
<!--    object-fit:cover;-->
    }
    .hero button{
        width: 200px;
        height: 40px;
        border: 1px solid white;
        background-color: #FFFFFF;
        transition: all 0.2s linear;
        color: white;
        font-size: 20px;
        font-weight: 700;
        cursor: pointer;
        letter-spacing: 4px;
        margin-top: 30px;
    }
    .hero button:hover{
        background-color: white;
        color: black;
    }
    .shadow{
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        background-color: #494848;
        opacity: 1;

    }
    .text{
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        color: white;
        padding: 0 100px;
    }
    </style>

    <div class="hero">
            <!-- <h1>Mi sozdayom budushee</h1>
            <button>Discover</button> -->
            <div class="shadow">

            </div>

            <div class="text">
                <br>
                <p></p>
                <h1>{{ news_detail.title }}</h1>
                <br>
                <img src='{{ news_detail.imageURL }}' alt="">
                <br>
              <div class="sometext">
                <h3>{{ news_detail.body }}</h3>
             {% if user.is_superuser %}
               <p align="right"><a href="{% url 'blog:edit_news' news_detail.pk %}" type="button" class="btn btn-md btn-outline-secondary">Edit</a> <a href="{% url 'blog:delete_news' news_detail.pk %}" type="button" class="btn btn-md btn-outline-secondary">Delete</a></p>
             {% endif %}
              </div>

            </div>
    </div>
{% endblock %}