account/api/urls.py
from django.urls import path, include
from account.api.views import accounts_view, account_register, account_login, account_logout, update_account


app_name = 'account_api'

urlpatterns = [
    path('account/', accounts_view),
    path('account_update/', update_account),
    path('register/', account_register),
    path('login', account_login),
    path('logout/', account_logout)
]

account/urls.py
from django.urls import path
from account.views import *

app_name = 'account'

urlpatterns = [
    path('home/', home, name='home_page'),
    path('signup/', registration_view, name='signup'),
    path('', authentication, name='signin'),
    path('signout/', signout_view, name='signout'),
    path('update/<int:pk>/', update_account, name='update_account'),

]

blog/urls.py
from django.urls import path

from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('marble/', blog_view, name='blog_view'),
    path('add_blog/', create_blog, name='add_blog'),
    path('detail/<int:pk>', detail_blog, name='blog_detail'),
    path('edit_blog/<int:pk>', edit_blog, name='edit_blog'),
    path('delete/<int:pk>/', delete_blog, name='delete_blog'),



    path('add_news/', create_news, name='news_add'),
    path('news/', news_view, name='news'),
    path('news_detail/<int:pk>', detail_news, name='news_detail'),
    path('edit_news/<int:pk>', edit_news, name='edit_news'),
    path('delete_news/<int:pk>/', delete_news, name='delete_news'),


    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('posts/', posts_view, name='posts'),
    path('add_comment_blogs/<int:pk>', blog_comment, name='blog_comment'),
    path('add_comment/<int:pk>', post_comment, name='post_comment'),

]

django_app/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),

    path('api/v1/', include('blog.api.urls')),
    path('api/v1/', include('account.api.urls')),

    path('api/v1/drf-auth/', include('rest_framework.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken'))
    # path('api/v1/auth/', include('djoser.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('blogs/', include('blog.urls')),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from uuid import uuid4
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class MyAccountManage(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have email')


        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email=self.normalize_email(email), password=password)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

def upload_location(instance, filename):
    ext = filename.split('.')[-1]
    file_path = "news_archive/{filename}".format(
        filename='{}.{}'.format(uuid4().hex, ext))
    return file_path


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name='email', max_length=50, unique=True)
    f_name = models.CharField(max_length=50, blank=True, null=True)
    l_name = models.CharField(max_length=50, blank=True, null=True)
    user_name = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField(upload_to=upload_location, blank=True, null=True)
    age = models.CharField(max_length=15, blank=True, null=True)
    date_birthday = models.DateTimeField(blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = MyAccountManage()

    @property
    def imageURL(self):
        try:
            url = str(self.image.url)
        except:
            url = ''
        return url

    def __str__(self):
        return str(self.email)

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    class Meta:
        app_label = 'account'

    # def get_absolute_url(self):
    #     return reverse("test:test", args=[str(self.id)])


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

account/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from account.models import Account
from account.models import Account


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text="Required. Add a valid email address")

    class Meta:
        model = Account
        fields = ['email', 'password1', 'password2']


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ['email', 'password']

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid inputs")


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = [
            'f_name',
            'l_name',
            'user_name',
            'image',
            'age',
            'date_birthday',
            'phone_number',
        ]
        enctype = "multipart/form-data"

class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('email', 'user_name',)

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email is already in use.' % account)



    def clean_username(self):
        if self.is_valid():
            user_name = self.cleaned_data['user_name']
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(user_name=user_name)
            except Account.DoesNotExist:
                return user_name
            raise forms.ValidationError('Username "%s" is already in use.' % user_name)

account/api/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from rest_framework import status
from rest_framework.decorators import action, api_view, permission_classes
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from account.models import Account
from account.api.serializers import AccountSerializers, RegistrationSerializer


@api_view(['POST', ])
def account_register(request):
    if request.method == 'POST':
        serializer = RegistrationSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
            account = serializer.save()
            data['response'] = "Successfully registered a new user."
            data['email'] = account.email
            # data['username'] = account.username
            token = Token.objects.get(user=account).key
            data['token'] = token
        else:
            data = serializer.errors
        return Response(data)


@api_view(["POST"])
def account_login(request):
    if request.method == "POST":
        email = request.data["email"]
        password = request.data["password"]
        authenticated_user = authenticate(request, email=email, password=password)
        if authenticated_user != None:
            # if (authenticated_user.is_authenticated and authenticated_user.is_superuser):
            if authenticated_user.is_authenticated:
                login(request, authenticated_user)
                return JsonResponse({"Message": "User is Authenticated. "})
            else:
                return JsonResponse({"message": "User is not authenticated. "})
        else:
            return JsonResponse({"Message": "Either User is not registered or password does not match"})


@api_view(["POST"])
def account_logout(request):
    print(request.user)
    logout(request)
    return JsonResponse({"message": "LoggedOut"})


@api_view(['GET', ])
@permission_classes((IsAuthenticated,))
def accounts_view(request):
    try:
        account = request.user
    except Account.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = AccountSerializers(account)
        return Response(serializer.data)


@api_view(['PUT', ])
@permission_classes((IsAuthenticated,))
def update_account(request):
    try:
        account = request.user
    except Account.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'PUT':
        serializer = AccountSerializers(account, data=request.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            data['response'] = "Account update success"
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

account/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from account.forms import AccountForm, AccountUpdateForm
from account.models import Account
from account.forms import RegisterForm, AccountAuthenticationForm


@login_required
def home(request):
    context = {}
    user = request.user
    sidebar = Account.objects.filter(id=user.id)
    context['sidebar'] = sidebar
    return render(request, 'home.html', context)


@login_required
def update_account(request, pk):
    context = {}
    user = request.user
    sidebar = Account.objects.filter(id=user.id)
    context['sidebar'] = sidebar

    if not user.is_authenticated:
        return redirect('account:signin')

    account_info = get_object_or_404(Account, pk=pk)

    if str(account_info.email) != str(user):
        return HttpResponse('Sorry, it is not your account.')

    if request.POST:
        form = AccountForm(request.POST or None, request.FILES or None, instance=account_info)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['message'] = 'Updated Successfully!'
            account_info = obj
            return redirect('account:home_page')

    form = AccountForm(
        initial={
            'email': account_info.email,
            'f_name': account_info.f_name,
            'l_name': account_info.l_name,
            'user_name': account_info.user_name,
            'image': account_info.image,
            'age': account_info.age,
            'date_birthday': account_info.date_birthday,
            'phone_number': account_info.phone_number
        }
    )
    account = Account.objects.filter(id=user.id)
    context['account'] = account
    context['form'] = form
    return render(request, 'personal_info.html', context)



def registration_view(request):
    context = {}
    if request.POST:
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')

            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('account:home_page')
        else:
            context['registration_form'] = form
    else:
        form = RegisterForm()
        context['registration_form'] = form
    return render(request, 'sign_up.html', context)


def authentication(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        return redirect('account:home_page')

    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect('account:home_page')

    else:
        form = AccountAuthenticationForm()

    context['login_form'] = form
    return render(request, 'sign_in.html', context)


def signout_view(request):
    logout(request)
    return redirect('account:signin')

account/templates/personal_info.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <style>
    body{
      padding-left:300px;
<!--      background-image:url("../../static/remont-3-komnantoj-kvartiry-133-kv-m-foto-22-4091.jpeg");-->
<!--        background-color: gray !important;-->
    }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
  </head>
<form method="post" enctype="multipart/form-data">
            {% csrf_token %}
    <div class="container">
      <main class="bg-light p-5">
          <div class="col-md-7 col-lg-8">
            <h4 class="mb-3 mt-5">ABOUT YOURSELF</h4>
            <form class="needs-validation" novalidate>
              <div class="row g-3">
                      <div class="col-sm-6">
                        <label for="firstName" class="form-label mt-4">First name</label>
                        <input type="text" class="form-control " id="firstName" name="f_name" placeholder="Enter your name" value="{{form.initial.f_name}}" required>
                        <div class="invalid-feedback">
                          Valid first name is required.
                        </div>

                      <div class="col-sm-6">
                        <label for="lastName" class="form-label mt-4">Last name</label>
                        <input type="text" class="form-control" id="lastName" name="l_name" placeholder="Enter your surname" value="{{form.initial.l_name}}" required>
                        <div class="invalid-feedback">
                          Valid last name is required.
                        </div>
                      </div>


                      <div class="col-sm-6">
                        <label for="email" class="form-label mt-4">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" value="{{form.initial.email}}" required>
                        <div class="invalid-feedback">
                          Valid last name is required.
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <label for="age" class="form-label mt-4">Age</label>
                        <input type="number" class="form-control" id="age" name="age" placeholder="Enter your age" value="{{form.initial.age}}" required>
                      </div>

<!--                      <div class="col-sm-7">-->
<!--                           <div class="col-6">-->
<!--                            <label for="sex" class="form-label mt-3">Sex</label>-->
<!--                          <input type="checkbox" class="checkbox" id="sex" name="sex" required>-->
<!--                        </div>-->
<!--                      </div>-->

                      <div class="col-12">
                        <label for="username" class="form-label mt-4">Username</label>
                        <div class="input-group has-validation">
                          <span class="input-group-text">@</span>
                          <input type="text" class="form-control" id="username" name="user_name" placeholder="Username" value="{{form.initial.user_name}}" required>
                        <div class="invalid-feedback">
                            Your username is required.
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <label for="date_of_birthday" class="form-label mt-4 my-2">Date of Birthday</label>
                        {% for date in account %}
                           <p>{{ date.date_birthday }}</p>
                        {% endfor %}
                          <input type="date" class="form-control " id="date_of_birthday" name="date_birthday" value="{{form.initial.date_birthday}}" required>

                      </div>

                      <div class="col-sm-6">
                        <label for="phone_number" class="form-label mt-4">Phone number</label>
                        <input type="text" class="form-control" id="phone_number" name="phone_number" value="{{form.initial.phone_number}}" required>
                      </div>
                      <div class="my-2">

                      </div>
                      <div class="col-12">
                        <label for="image" class="form-label mt-4">Profile photo</label>
                      {% for image in account %}
                           <img height="300px" width="100%" src='{{ image.imageURL }}' alt="">
                      {% endfor %}
                        <input type="file" class="form-control" id="image" name="image" value="" required>
                        <div class="invalid-feedback">
                          Please enter your photo.
                        </div>
                      </div>
                    <hr class="my-4">
                    <button class="w-100 btn btn-primary btn-lg" type="submit">Save</button>
                    </div>
                  </form>
            </div>
      </main>
    </div>
</form>
  </body>
{% endblock %}

account/templates/sign_in.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Signin Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link href="assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

 </style>
    <link href="signin.css" rel="stylesheet">
  </head>

<form class="form-signin" method="post">{% csrf_token %}
  <body style="background-color:#424242" class="text-center ">
      <main style="margin:100px auto" class="form-signin w-25">
        <form>
<!--          <img class="mb-4" src="{% static 'bootstrap-logo.svg' %}" alt="" width="72" height="57">-->
          <h1 style="color:white">MARBLE</h1>
          <p>
            <br>
          <div class="form-floating">
            <input type="email" class="form-control mt-2"  id="floatingInput" name="email" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
          </div>

          <div class="form-floating">
            <input type="password" class="form-control mt-2" id="password" name="password" placeholder="Password">
            <label for="password">Password</label>
          </div>

          <div class="checkbox mb-3">
            <label style="color:white">
              <input type="checkbox" value="remember-me"> Remember me
            </label>
          </div>
          {% for field in login_form %}
          <p>
              {% for error in field.errors %}
                <p style="color: red;">{{ error }}</p>
              {% endfor %}
          {% endfor %}
          {% if login_form.non_field_errors %}
            <div style="color: red;">
              <p>{{ login_form.non_field_errors }}</p>
            </div>
          {% endif %}
          <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
          <h5 style="color:white">Need an account?    <a style="text-decoration:none" href="{% url 'account:signup' %}">Sign up</a></h5>
          <p class="mt-5 mb-3 text-muted-white text-white">© 2017–2022</p>
        </form>
      </main>
  </body>

</form>

account/templates/sign_up.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Signin Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    

    

<link href="dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>

<form method="post">
    {% csrf_token %}

    <body style="background-color:#424242" class="text-center">

  <main style="margin:100px auto" class="form-signin w-25">
    <form>
          <h1 style="color:white">MARBLE</h1>
          <p>
            <br>
      <div class="form-floating">
        <input type="email" class="form-control mt-2" id="floatingInput" name="email" placeholder="name@example.com">
        <label for="floatingInput">Email address</label>
      </div>

      <div class="form-floating">
        <input type="password" class="form-control mt-2" id="password1" name="password1" placeholder="Password">
        <label for="password1">Password</label>
      </div>

      <div class="form-floating">
        <input type="password" class="form-control mt-2" id="password2" name="password2" placeholder="Validate password">
        <label for="password2">Validate password</label>
      </div>

      {% for field in registration_form %}
        <p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
      {% endfor %}
      {% if registration_form.non_field_errors %}
      <div style="color: red">
        <p>{{registration_form.non_field_errors}}</p>
      </div>

      {% endif %}


      <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
      <p class="mt-5 mb-3 text-white">© 2017–2022</p>
    </form>
  </main>



    </body>
</form>
</html>